version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - server
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
  server:
    build: ./server
    ports:
      - 4000:4000
      - 5555:5555
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}